# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3179045771c24c9c3c4996aac3ad5a275e203bbfd48ad6151f85372dfb9862b4e3228e945744b1d2394afc6e0efe6c61f168ec71f69fbf445989964b5f4737d7

test:
  secret_key_base: d4c2f2d090d961624f6d00e31620c5a9026b716e4265d726d755199bfd95d3cd569b0c54af232f7be11a05abcb146274add734d79a133a5f3b1402ba9073892e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
